#!/bin/bash

# Create cookies directory
mkdir -p /app/cookies

# Create a basic Netscape format cookies file
cat > /app/cookies/cookies.txt << 'EOL'
# Netscape HTTP Cookie File
# https://curl.haxx.se/rfc/cookie_spec.html
# This file is generated by docker build. Replace with actual cookies in production.

.youtube.com	TRUE	/	TRUE	2147483647	CONSENT	YES+cb
.youtube.com	TRUE	/	TRUE	2147483647	VISITOR_INFO1_LIVE	random_id
.youtube.com	TRUE	/	TRUE	2147483647	LOGIN_INFO	random_token
.youtube.com	TRUE	/	TRUE	2147483647	SID	random_sid
.youtube.com	TRUE	/	TRUE	2147483647	__Secure-1PSID	random_psid
.youtube.com	TRUE	/	TRUE	2147483647	__Secure-3PSID	random_3psid
.youtube.com	TRUE	/	TRUE	2147483647	HSID	random_hsid
.youtube.com	TRUE	/	TRUE	2147483647	SSID	random_ssid
.youtube.com	TRUE	/	TRUE	2147483647	APISID	random_apisid
.youtube.com	TRUE	/	TRUE	2147483647	SAPISID	random_sapisid
.youtube.com	TRUE	/	TRUE	2147483647	__Secure-1PAPISID	random_1papisid
.youtube.com	TRUE	/	TRUE	2147483647	__Secure-3PAPISID	random_3papisid
.youtube.com	TRUE	/	TRUE	2147483647	YSC	random_ysc
.youtube.com	TRUE	/	TRUE	2147483647	PREF	random_pref

.google.com	TRUE	/	TRUE	2147483647	CONSENT	YES+cb
.google.com	TRUE	/	TRUE	2147483647	SID	random_sid
.google.com	TRUE	/	TRUE	2147483647	__Secure-1PSID	random_psid
.google.com	TRUE	/	TRUE	2147483647	__Secure-3PSID	random_3psid
.google.com	TRUE	/	TRUE	2147483647	HSID	random_hsid
.google.com	TRUE	/	TRUE	2147483647	SSID	random_ssid
.google.com	TRUE	/	TRUE	2147483647	APISID	random_apisid
.google.com	TRUE	/	TRUE	2147483647	SAPISID	random_sapisid
.google.com	TRUE	/	TRUE	2147483647	__Secure-1PAPISID	random_1papisid
.google.com	TRUE	/	TRUE	2147483647	__Secure-3PAPISID	random_3papisid
EOL

# Create a symbolic link for youtube.cookies
ln -sf /app/cookies/cookies.txt /app/cookies/youtube.cookies

# Set permissions
chmod 644 /app/cookies/cookies.txt
chmod 644 /app/cookies/youtube.cookies 